# CHAPTER 7
# Data Wrangling: Clean,Transform,Merge,Reshape

In [2]:
# 모듈 불러오기
import numpy as np
import pandas as pd #import A as B 구문을 사용하면 B라는 단어를 A처럼 사용할 수가 있다. (영단어 as의 의미처럼 생각하면 됨) 

# 7.1 데이터 합치기 (Combining and Merging Data Sets)
## 7.1-1 데이터베이스 스타일로 DataFrame 합치기 (Database-style DataFrame Merges)

In [3]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})
df1
# index는 숫자로 입력되며 column은 코드입력순​df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})
df1
# index는 숫자로 입력되며 column은 코드입력순서와 무관하고 알파벳 순서대로 차례로 배열된다.서와 무관하고 알파벳 순서대로 차례로 배열된다.
# k는 d 보다 뒤순서이므로 뒤에 배열된다.
# 'key'의 데이터 개수와 'data1'의 데이터 개수가 같아야한다.

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [21]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'], 'data2': range(3)})
df2

data2 key
0      0   a
1      1   b
2      2   d

### - 이름이 겹치는 열을 기준으로 병합을 하는 merge 함수

In [7]:
pd.merge(df2, df1) #merge 함수는 앞에 오는 인자를 기준으로 배열을 한다.

data2 key  data1
0      0   a      2
1      0   a      4
2      0   a      5
3      1   b      0
4      1   b      1
5      1   b      6

In [8]:
pd.merge(df1, df2) #이름이 겹치는 걸 기준으로 하기에 생략된 값들이 존재함

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

#### 만약 두 데이터프레임간 겹치지 않는 key도 결과에 나오게끔 하고 싶다면, how='outer' 옵션을 사용하면 된다.

In [9]:
pd.merge(df1, df2, how='outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

<font color="RED"> + 더 알아보기</font>
<br>pandas.merge는 디폴트로 'inner merge'을 가지기에 두 데이터프레임의 intersection(교차점)만을 결과에 보여준다.<br>
그런데 위의 outer로 옵션을 변경해주면 교차점 이외의 값도 볼 수 있다는 것을 확인할 수 있다.<br> <br>
pandas.merge에서 두 데이터프레임 병합 시 how= 옵션 뒤에 쓸 수 있는 것은 'left', 'right', 'out', 'inner' 네 가지가 있는데,
- how='left': 코드에서 왼쪽에 적힌 데이터프레임의 key 값에 대해서만 병합해서 보여준다. 
- how='right': 코드에서 오른쪽에 적힌 데이터프레임의 key 값에 대해서만 병합해서 보여준다. 
- how='outer': 두 데이터프레임에 있는 모든 key 값을 병합해서 보여준다.
- how='inner'(디폴트값): 두 데이터프레임에서 교차되는(두 데이터프레임에 다 들어 있는) key 값들만을 병합해서 보여준다.


In [23]:
pd.merge(df1, df2, how='left')

data1 key  data2
0      0   b    1.0
1      1   b    1.0
2      2   a    0.0
3      3   c    NaN
4      4   a    0.0
5      5   a    0.0
6      6   b    1.0

In [24]:
pd.merge(df1, df2, how='right')

data1 key  data2
0    0.0   b      1
1    1.0   b      1
2    6.0   b      1
3    2.0   a      0
4    4.0   a      0
5    5.0   a      0
6    NaN   d      2

### - merge 함수를 쓰고 싶은데 공통된 이름이 없다면??

In [25]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})
df3

data1 lkey
0      0    b
1      1    b
2      2    a
3      3    c
4      4    a
5      5    a
6      6    b

In [26]:
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'], 'data2': range(3)})
df4

data2 rkey
0      0    a
1      1    b
2      2    d

In [27]:
pd.merge(df3, df4) #오류 -> No common columns to perform merge on

MergeError: No common columns to perform merge on

In [30]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey') # lkey(df3) 와 rkey(df4)를 바꿔주면 오류발생

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

 #### + <font color="blue">하나</font></b>의 데이터프레임이 아닌 <font color="blue">두 데이터프레임</font> </b> 모두 한 key에 해당되는 value가 여러개일 때

In [52]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [53]:
df2 = pd.DataFrame({'key': ['a', 'b', 'a', 'b', 'd'], 'data2': range(5)})
df2

data2 key
0      0   a
1      1   b
2      2   a
3      3   b
4      4   d

In [54]:
# on='key'이므로 key라는 열을 기준으로 병합되었고, how=left이므로 df1에 있는 key 값들을 기준으로 병합되었음을 알 수 있다.
pd.merge(df1, df2, on='key', how='left')

data1 key  data2
0       0   b    1.0
1       0   b    3.0
2       1   b    1.0
3       1   b    3.0
4       2   a    0.0
5       2   a    2.0
6       3   c    NaN
7       4   a    0.0
8       4   a    2.0
9       5   b    1.0
10      5   b    3.0

 ### - key를 조합해서 여러 개 쓰는 법은 <font color="blue">on</font>으로 목록을 넘겨야 한다!

In [55]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'], 'key2': ['one', 'two', 'one'], 'lval': [1, 2, 3]})
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [56]:
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'], 'key2': ['one', 'one', 'one', 'two'], 'rval': [4, 5, 6, 7]})
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [57]:
pd.merge(left, right, on=['key1', 'key2'], how='outer')
# 'key1'과 'key2'의 조합을 기준으로 병합을 실시함

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [59]:
pd.merge(left, right, on=['key2'], how='outer')
# 'key1'과 'key2'의 조합을 기준으로 병합을 실시함

key1_x key2  lval key1_y  rval
0    foo  one     1    foo     4
1    foo  one     1    foo     5
2    foo  one     1    bar     6
3    bar  one     3    foo     4
4    bar  one     3    foo     5
5    bar  one     3    bar     6
6    foo  two     2    bar     7

#### + pandas.merge의 추가적인 옵션들이 보고 싶다면 교재 181쪽 하단에 있는 Table 7-1 을 참고

## 7.1-2 색인 머지하기 (Merging on Index) 
데이터프레임에 있는 key 값의 <b> <font color="red"> 인덱스 </font> </b>를 병합의 기준으로 삼으려 할 때, <br />
<b> <font color="blue"> 'left_index=True' 나 'right_index=True' </font> </b> (혹은 둘 다) 옵션들을 지정하여<br />
병합에 사용되는 기준 key들을 인덱스 값들로 지정할 수 있다.

In [60]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'], 'value': range(6)})
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [61]:
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])
right1

group_val
a        3.5
b        7.0

In [124]:
# right1의 index 값을 기준으로 left1과 right1을 병합했다.
pd.merge(left1, right1, left_on='key', right_index=True)
# 병합 결과 left1에서 key가 c인 값은 출력되지 않는다. right1에서 c는 존재하지 않아 false로 취급되기 때문에
# a, b가 모두 index에 들어가있으므로 right_index = True

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [65]:
# 마찬가지로 how='outer' 옵션을 통해 두 데이터프레임의 key값들의 교집합뿐만이 아닌 합집합을 결과로 나오게 할 수도 있다.
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

### - 인덱스가 계층적 구조로 이루어져 있다면

In [70]:
lefth = pd.DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
                      'key2': [2000, 2001, 2002, 2001, 2002],
                      'data': np.arange(5.)})
lefth

data    key1  key2
0   0.0    Ohio  2000
1   1.0    Ohio  2001
2   2.0    Ohio  2002
3   3.0  Nevada  2001
4   4.0  Nevada  2002

In [68]:
righth = pd.DataFrame(np.arange(12).reshape((6, 2)),
                      index=[['Nevada', 'Nevada', 'Ohio', 'Ohio', 'Ohio', 'Ohio'],
                             [2001, 2000, 2000, 2000, 2001, 2002]],
                      columns=['event1', 'event2'])
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [75]:
# 일단 지역이름으로 병합하라고 명령 
pd.merge(lefth, righth, left_on='key1', right_index=True)

ValueError: len(left_on) must equal the number of levels in the index of "right"

righth의 인덱스 계층이 2개여서 에러가 뜬다. <br>
그래서 기준(key)을 두 개 지정해주어야 한다. <br>
즉, 여러 개의 기준 열을 리스트형태로 지정해줘야 한다. <br>
이 경우, <b> <font color="blue"> lefth의 'key1'과 'key2'이라는 열과 righth의 인덱스 </font> </b> 를 기준으로 병합된다.

In [76]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)
# lefth에 있던 Nevada 2002는 출력되지 않는다. righth의 index 중에서 Nevada 2002가 없기 때문에

data    key1  key2  event1  event2
0   0.0    Ohio  2000       4       5
0   0.0    Ohio  2000       6       7
1   1.0    Ohio  2001       8       9
2   2.0    Ohio  2002      10      11
3   3.0  Nevada  2001       0       1

In [77]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True, how='outer')
#NaN 값을 포함해서 포괄적으로 데이터를 추출하고 싶다면 how='outer'이라고 지정해준다.

data    key1  key2  event1  event2
0   0.0    Ohio  2000     4.0     5.0
0   0.0    Ohio  2000     6.0     7.0
1   1.0    Ohio  2001     8.0     9.0
2   2.0    Ohio  2002    10.0    11.0
3   3.0  Nevada  2001     0.0     1.0
4   4.0  Nevada  2002     NaN     NaN
4   NaN  Nevada  2000     2.0     3.0

#### + 두 데이터프레임 모두의 인덱스를 사용하여 병합하는 것도 가능

In [78]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                     index=['a', 'c', 'e'],
                     columns=['Ohio', 'Nevada'])
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [79]:
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                      index=['b', 'c', 'd', 'e'], 
                      columns=['Missouri', 'Alabama'])
right2

Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [80]:
pd.merge(left2, right2, left_index=True, right_index=True)

Ohio  Nevada  Missouri  Alabama
c   3.0     4.0       9.0     10.0
e   5.0     6.0      13.0     14.0

#### +<b> how='outer' </b>을 이용한다면  <font color="red"> NaN 값도 포함</font>시켜서 추출해준다

In [81]:
pd.merge(left2, right2, how='outer', left_index=True, right_index=True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

## 7.1-3 축따라 이어붙이기 (Concatenating Along an Axis)

Concatenate란? to link or join together  
NumPy는 Numpy array들로 데이터를 묶는 'concatenate' 함수를 가지고 있다.

In [82]:
arr = np.arange(12).reshape((3, 4)) # 0부터 11까지의 정수를 3행 4열의 형태로 배열함
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### - numpy.concatenate로 여러 개의 배열을 하나로 합쳐보자!

In [83]:
np.concatenate([arr, arr]) # arr와 arr을 세로로 이어 붙임!

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
# 'axis=1'은 가로로 붙이기! numpy.concatenate의 인자로 추가하는 방식으로 구현할 수 있다.
np.concatenate([arr, arr], axis=1) #axis=0이 디폴트 값임

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [90]:
arr1 = np.arange(8).reshape((2,4))
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [92]:
np.concatenate([arr, arr1])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [93]:
np.concatenate([arr, arr1], axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

이번에는 인덱스가 서로 겹치지 않는 세 개의 Series를 지정해보자. <br>
Series라는 개념을 이해하기 위해 첫 번째 Series만 출력!

In [94]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s1

a    0
b    1
dtype: int64

In [95]:
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])

### - pandas.concat으로 합쳐보자!
pandas.concat에 리스트 형태로 결합해서 돌려보면 모든 인덱스와 그에 해당하는 값들을 합쳐줌.

In [96]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

<FONT COLOR="RED">+ 주의!</FONT>
  <BR>axis=1의 다른 의미! <br>
- <font color="blue"> Series를 concat </font> 할 때 axis=1로 설정하면 <font color="blue"> 데이터프레임 </font>으로 반환된다!<br>
- <font color="green"> array를 concat </font>할 때 axis=1로 설정하면 <font color="green"> 가로로 붙이는 것 </font>

In [97]:
pd.concat([s1, s2, s3], axis=1)
# NaN 값도 포함해서 출력을 해주는 pandas.concat

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [98]:
# 값이 겹치도록 새로운 Series를 생성해보자.
s4 = pd.concat([s1 * 5, s3])
s4

a    0
b    5
f    5
g    6
dtype: int64

In [99]:
# s1과 s4를 열로 이어붙여서 데이터프레임을 만들었다.
pd.concat([s1, s4], axis=1) #column명이 0인 게 앞에 있는 s1, column명이 1인 게 뒤에 있는 s4를 의미함

0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [100]:
# 옵션을 join='inner'로 지정하면 NaN 값을 제외하고 보여준다..
pd.concat([s1, s4], axis=1, join='inner')

0  1
a  0  0
b  1  5

### - 인덱스를 <font color="BLUE"> 계층적 </font> 으로 지정하고 싶다면 <font color="BLUE"> 'keys=[]' </font>옵션을 사용!

In [102]:
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])
result
#차례대로 s1, s2, s3에 해당하는 것이다.

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [103]:
# axis=1으로 (데이터프레임을 만든다 / 가로로 붙일 수 있다.)
pd.concat([s1, s2, s3], axis=1, keys=['one', 'two', 'three'])
## keys=[]' 옵션으로 지정한 값들이 데이터프레임의 열 header들이 된다.

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

이는 데이터프레임들을 결합할 때도 똑같이 적용된다.

In [104]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2),
                   index=['a', 'b', 'c'],
                   columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2),
                   index=['a', 'c'],
                   columns=['three', 'four'])

pd.concat([df1, df2], axis=1, keys=['level1', 'level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [105]:
pd.concat([df1, df2], axis=0, keys=['level1', 'level2'])
# column은 알파벳 순서로 배열되어있고, df1은 level1에 df2는 level2에 배열되어 있음

four  one  three  two
level1 a   NaN  0.0    NaN  1.0
       b   NaN  2.0    NaN  3.0
       c   NaN  4.0    NaN  5.0
level2 a   6.0  NaN    5.0  NaN
       c   8.0  NaN    7.0  NaN

<b> <font color="BLUE">딕셔너리 형태</font> </b>로 결합할 객체들을 전달한다면, <br>
딕셔너리의 <b> <font color="BLUE"> 키 값들이</font> </b> 'keys=[]' 옵션에 <b> <font color="BLUE"> 자동으로</font> </b> 활용된다.

In [107]:
pd.concat({'level1': df1, 'level2': df2}, axis=1)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [108]:
pd.concat({'level1': df1, 'level2': df2}, axis=0)

four  one  three  two
level1 a   NaN  0.0    NaN  1.0
       b   NaN  2.0    NaN  3.0
       c   NaN  4.0    NaN  5.0
level2 a   6.0  NaN    5.0  NaN
       c   8.0  NaN    7.0  NaN

# 7.2 재형성과 피벗 (Reshaping and Pivoting)
- 재형성 : 표 형식의 데이터를 재배치하는 다양한 기본 연산<br />

In [109]:
#문자열을 row와 column의 index로 가지는 DataFrame
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                 index = pd.Index(['Ohio', 'Colorado'], name='state'),
                 columns = pd.Index(['one', 'two', 'three'], name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [110]:
#'number'가 row로 바뀌었음
result = data.stack()
result #Dataframe -> Series

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [111]:
#'state'가 column으로 바뀌었음
data.unstack() #Dataframe -> Series

number  state   
one     Ohio        0
        Colorado    3
two     Ohio        1
        Colorado    4
three   Ohio        2
        Colorado    5
dtype: int32

In [112]:
#'number'가 column으로 바뀌었음
result.unstack() #Series -> DataFrame

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

stack()과 unstack()은 Series는 Dataframe으로, Dataframe은 Series로 반환한다. <br>
다만 Series에 stack()을 적용하는 것은 불가능하다.

In [113]:
s1 = pd.Series([0,1,2,3], index = ['a','b','c','d'])
s2 = pd.Series([4,5,6], index = ['c','d','e'])
data2 = pd.concat([s1, s2], keys = ['one','two'])

In [114]:
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [115]:
data2.unstack() #NaN 데이터도 추출

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [116]:
#NaN 데이터가 발생한 칼럼을 다시 row로 돌리기
data2.unstack().stack() #NaN 데이터를 생략한다.

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [117]:
#NaN 데이터까지 포함시키고자 한다면
data2.unstack().stack(dropna=False) #dropna=False 옵션 추가

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

## pivot 메서드 : set_index()와 unstack()을 같이 쓴 결과와 같다.
즉, <b> <font color="red"> 계층적 색인</font> </b>을 만들고 <b> <font color="red"> 형태를 변경 </font> </b>하는 것을 동시에 수행하는 메소드이다. <br>
자세한 내용은 pdf 192-193 page 참조

In [118]:
data = {
    "도시": [
        "서울", "서울", "서울", "부산", "부산", "부산", "인천", "인천"
    ],
    "연도": [
        "2015", "2010", "2005", "2015", "2010", "2005", "2015", "2010"
    ],
    "인구": [
        9904312, 9631482, 9762546, 3448737, 3393191, 3512547, 2890451, 2632035
    ],
    "지역": [
        "수도권", "수도권", "수도권", "경상권", "경상권", "경상권", "수도권", "수도권"
    ]
}
columns = ["도시", "연도", "인구", "지역"]
df1 = pd.DataFrame(data, columns=columns)
df1

도시    연도       인구   지역
0  서울  2015  9904312  수도권
1  서울  2010  9631482  수도권
2  서울  2005  9762546  수도권
3  부산  2015  3448737  경상권
4  부산  2010  3393191  경상권
5  부산  2005  3512547  경상권
6  인천  2015  2890451  수도권
7  인천  2010  2632035  수도권

In [119]:
df1.pivot("도시", "연도", "인구")

연도       2005       2010       2015
도시                                 
부산  3512547.0  3393191.0  3448737.0
서울  9762546.0  9631482.0  9904312.0
인천        NaN  2632035.0  2890451.0

In [120]:
df1.set_index(["도시", "연도"])[["인구"]].unstack()

인구                      
연도       2005       2010       2015
도시                                 
부산  3512547.0  3393191.0  3448737.0
서울  9762546.0  9631482.0  9904312.0
인천        NaN  2632035.0  2890451.0

In [122]:
df1.pivot("지역", "연도", "인구")

ValueError: Index contains duplicate entries, cannot reshape

# 7.3 Data Transformation
## 7.3.1 Removing Duplicates(중복 제거)

In [127]:
import pandas as pd
from pandas import Series,DataFrame

In [128]:
data = DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
                  'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

#### Duplicated() : 각 행이 중복인지 아닌지를 True or False로 반환
#### drop.duplicates() : Duplicated()의 True 값을 drop 시킴

In [4]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [5]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [129]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [7]:
# 'k1'열만을 고려해 drop_duplicates 실행
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
3  two   3   3

In [132]:
# 기본적으로 duplicated()와 drop_duplicstes()는 첫번째 값을 유지하지만,
# keep='last'를 사용하면 마지막 값을 취함
data.drop_duplicates(['k1', 'k2'], keep='last')
#last 말고 first도 사용

k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

## 7.3.2 Transforming Data Using a Function or Mapping
### Array, Series, Column을 기반으로 변환을 수행할 수 있다.

### * mapping : key와 value의 쌍을 이용해 데이터를 관리하는 구조
#### - key : 저장된 데이터를 식별하기 위함
#### - value : 각 키에 연결된 데이터
#### - key를 알면 원하는 데이터를 꺼낼 수 있음
#### - map을 사용하면 요소 기반 변환과 기타 데이터 정리작업을 손쉽게 수행 가능

In [10]:
data = DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
                  'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [11]:
# 각 음식에 해당하는 동물 추가
meat_to_animal = {'bacon':'pig','pulled pork': 'pig','pastrami':'cow',
                  'corned beef':'cow','honey ham':'pig','nova lox':'salmon'}

In [12]:
# map(str.lower) : data의 food행의 대문자를 소문자로 변환
# meat_to_animal은 소문자로 이루어져있기 때문에 food의 대문자를 소문자로 바꿔줘야한다.
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [14]:
data = Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [15]:
import numpy as np

In [18]:
## 여기서 -999는 missing data
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [19]:
data.replace([-999, -1000], np.nan) # -999와 -1000을 missing data로 처리

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [20]:
## 방법1
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [21]:
## 방법2
data.replace({-999: np.nan, -1000: 0}) 

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

## 7.3.4 Renaming Axis Indexes

In [22]:
data = DataFrame(np.arange(12).reshape((3, 4)),
                 index=['Ohio', 'Colorado', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [23]:
## map()을 이용해 'index'를 대문자로 수정
data.index.map(str.upper)

Index(['OHIO', 'COLORADO', 'NEW YORK'], dtype='object')

In [24]:
data.index = data.index.map(str.upper)
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [25]:
data # 원본이 대문자로 수정된 것을 확인할 수 있다

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [26]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [27]:
data # 원본은 수정되지 않음을 확인

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [28]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'}) #직접 지정해서 renaming 가능

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [29]:
## inplace=True : 원본에 저장하기
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA     0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

## 7.3.5 Discretization and Binning
### 연속데이터를 나누는 작업

In [30]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [31]:
## 18-25 / 26-35 / 36-60 / 61이상으로 구간을 묶어줌
bins = [18, 25, 35, 60, 100]

In [32]:
## cut() : bins를 사용해 구간으로 끊어줌
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [33]:
## 구간을 array로 나타냄
cats.labels

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: 'labels' is deprecated. Use 'codes' instead
  


array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [34]:
## categories : 범주를 보여줌
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [35]:
## value_counts() : 구간값의 갯수를 나타냄
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

#### 'right = False' : 기준의 오른쪽을 열린 괄호
#### 'right = True' : 기준의 오른쪽을 닫힌 괄호

In [36]:
pd.cut(ages, [18, 26, 36, 61, 100], right=True)

[(18, 26], (18, 26], (18, 26], (26, 36], (18, 26], ..., (26, 36], (36, 61], (36, 61], (36, 61], (26, 36]]
Length: 12
Categories (4, interval[int64]): [(18, 26] < (26, 36] < (36, 61] < (61, 100]]

In [37]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [38]:
## 'labels = group_names': bins의 구간에 'group_names'을 할당
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [MiddleAged < Senior < YoungAdult < Youth]

#### data의 최소,최댓값을 기반으로 동일한 길이로 cut도 가능

In [39]:
data = np.random.rand(20) # 0~1 uniform 한 확률로 난수 생성
data

array([ 0.14073198,  0.38311019,  0.9404588 ,  0.45963995,  0.23906211,
        0.42543985,  0.48889302,  0.18073505,  0.80055511,  0.29585883,
        0.04596491,  0.57202968,  0.200467  ,  0.72021751,  0.53484719,
        0.3053239 ,  0.48313059,  0.72005052,  0.49169746,  0.79440852])

In [40]:
pd.cut(data, 4, precision=2) #precision :소수점 자릿수

[(0.045, 0.27], (0.27, 0.49], (0.72, 0.94], (0.27, 0.49], (0.045, 0.27], ..., (0.27, 0.49], (0.27, 0.49], (0.72, 0.94], (0.27, 0.49], (0.72, 0.94]]
Length: 20
Categories (4, interval[float64]): [(0.045, 0.27] < (0.27, 0.49] < (0.49, 0.72] < (0.72, 0.94]]

#### qcut() : 구간별 같은 크기의 값을 얻을 수 있음

In [41]:
data = np.random.randn(1000) # 가우시안 표준정규분포을 따르는 난수 생성

In [42]:
cats = pd.qcut(data, 4)
cats

[(-3.796, -0.691], (-0.691, -0.0369], (-3.796, -0.691], (-0.0369, 0.705], (-3.796, -0.691], ..., (-3.796, -0.691], (-3.796, -0.691], (0.705, 3.464], (0.705, 3.464], (-0.0369, 0.705]]
Length: 1000
Categories (4, interval[float64]): [(-3.796, -0.691] < (-0.691, -0.0369] < (-0.0369, 0.705] < (0.705, 3.464]]

In [43]:
pd.value_counts(cats)

(0.705, 3.464]       250
(-0.0369, 0.705]     250
(-0.691, -0.0369]    250
(-3.796, -0.691]     250
dtype: int64

## 7.3.6 Detecting and Filtering Outliers

In [44]:
import numpy as np

In [134]:
np.random.seed(12345)

data = DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [46]:
col = data[3] #4번째 열 값 이용
col[np.abs(col) > 3] # 절댓값 3 이상인 값을 불러옴

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

In [47]:
# any : 조건을 만족하는 값의 모든 행의 값을 불러옴
data[(np.abs(data) > 3).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [48]:
# np.sign(): x<0이면 -1 / x==0이면 0 / x>0이면 1 을 입력해 이상치 수정 가능

data[np.abs(data) > 3] = np.sign(data) * 3
data.describe() 

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

## 7.3.7 Permutation and Random Sampling

In [49]:
df = DataFrame(np.arange(5 * 4).reshape(5, 4))

In [50]:
# np.random.permutation() : dataframe의 행의 순서를 임의로 변경
sampler = np.random.permutation(5)
sampler

array([1, 0, 2, 3, 4])

In [51]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [52]:
df.take(sampler) ## permutation 값에 따라 행렬값 변화

0   1   2   3
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [53]:
df.take(np.random.permutation(len(df))[:2]) #원하는 크기로 subset 만들기

0   1   2   3
1   4   5   6   7
3  12  13  14  15

In [54]:
bag = np.array([5, 7, -1, 6, 4])

In [55]:
sampler = np.random.randint(0, len(bag), size=10) #균일 분포의 정수 난수
sampler

array([4, 4, 2, 2, 2, 0, 3, 0, 4, 1])

In [56]:
draws = bag.take(sampler)
draws # sampler에 따라 permutation

array([ 4,  4, -1, -1, -1,  5,  6,  5,  4,  7])

## 7.3.8 Computing Indicator/Dummy Variables 

In [136]:
df = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                 'data1': range(6)})

In [137]:
#get_dummy() : 범주형 변수를 'dummy' or 'indicator' 행렬로 변환
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [139]:
#prefix= 'key' : 'key'라는 접두사 추가
dummies = pd.get_dummies(df['key'], prefix='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [143]:
df_with_dummy = df[['data1']].join(dummies) # df[['data1']]은 dataframe이다.
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

#### dataframe의 행이 여러 카테고리에 속하는 경우

In [205]:
mnames = ['movie_id', 'title', 'genres']
import os
import pandas as pd
os.chdir("C:/Users/user/Desktop")

In [207]:
movies = pd.read_table('movies.dat', sep='::', header=None,
                        names=mnames)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [66]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [216]:
genre_iter = (set(x.split('|')) for x in movies.genres)
genres = sorted(set.union(*genre_iter)) #장르 목록 추출

['Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western']

In [218]:
# zeros() : 해당 배열에 전부 '0'을 넣음
dummies = DataFrame(np.zeros((len(movies), len(genres))), columns=genres)
dummies

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
1        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
2        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
4        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
5        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
6        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
7        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
8        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
9        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
10       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
11       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
12       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
13       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
14       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
15       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
16       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
17       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
18       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
19       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
20       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
21       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
22       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
23       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
24       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
25       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
26       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
27       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
28       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
29       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
...      ...        ...        ...         ...     ...    ...          ...   
3853     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3854     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3855     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3856     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3857     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3858     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3859     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3860     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3861     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3862     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3863     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3864     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3865     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3866     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3867     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3868     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3869     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3870     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3871     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3872     0.0        0.0     

In [223]:
#해당 장르에 1입력하는 함수
for i, gen in enumerate(movies.genres):
    dummies.loc[i, gen.split('|')] = 1
dummies

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0        0.0        0.0        1.0         1.0     1.0    0.0          0.0   
1        0.0        1.0        0.0         1.0     0.0    0.0          0.0   
2        0.0        0.0        0.0         0.0     1.0    0.0          0.0   
3        0.0        0.0        0.0         0.0     1.0    0.0          0.0   
4        0.0        0.0        0.0         0.0     1.0    0.0          0.0   
5        1.0        0.0        0.0         0.0     0.0    1.0          0.0   
6        0.0        0.0        0.0         0.0     1.0    0.0          0.0   
7        0.0        1.0        0.0         1.0     0.0    0.0          0.0   
8        1.0        0.0        0.0         0.0     0.0    0.0          0.0   
9        1.0        1.0        0.0         0.0     0.0    0.0          0.0   
10       0.0        0.0        0.0         0.0     1.0    0.0          0.0   
11       0.0        0.0        0.0         0.0     1.0    0.0          0.0   
12       0.0        0.0        1.0         1.0     0.0    0.0          0.0   
13       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
14       1.0        1.0        0.0         0.0     0.0    0.0          0.0   
15       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
16       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
17       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
18       0.0        0.0        0.0         0.0     1.0    0.0          0.0   
19       1.0        0.0        0.0         0.0     0.0    0.0          0.0   
20       1.0        0.0        0.0         0.0     1.0    0.0          0.0   
21       0.0        0.0        0.0         0.0     0.0    1.0          0.0   
22       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
23       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
24       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
25       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
26       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
27       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
28       0.0        1.0        0.0         0.0     0.0    0.0          0.0   
29       0.0        0.0        0.0         0.0     0.0    0.0          0.0   
...      ...        ...        ...         ...     ...    ...          ...   
3853     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3854     0.0        0.0        0.0         0.0     1.0    0.0          0.0   
3855     0.0        0.0        0.0         0.0     1.0    0.0          0.0   
3856     0.0        1.0        0.0         0.0     0.0    0.0          0.0   
3857     0.0        1.0        0.0         0.0     0.0    0.0          0.0   
3858     0.0        0.0        0.0         0.0     1.0    0.0          0.0   
3859     0.0        0.0        0.0         0.0     1.0    0.0          0.0   
3860     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3861     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3862     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3863     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3864     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3865     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3866     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3867     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3868     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3869     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3870     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3871     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3872     0.0        0.0     

In [224]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[3]

#해당 영화 장르는 1 / 해당하지 않는 장르는 0으로 표현

movie_id                                    4
title                Waiting to Exhale (1995)
genres                           Comedy|Drama
Genre_Action                                0
Genre_Adventure                             0
Genre_Animation                             0
Genre_Children's                            0
Genre_Comedy                                1
Genre_Crime                                 0
Genre_Documentary                           0
Genre_Drama                                 1
Genre_Fantasy                               0
Genre_Film-Noir                             0
Genre_Horror                                0
Genre_Musical                               0
Genre_Mystery                               0
Genre_Romance                               0
Genre_Sci-Fi                                0
Genre_Thriller                              0
Genre_War                                   0
Genre_Western                               0
Name: 3, dtype: object

In [71]:
values = np.random.rand(10)
values

array([ 0.75603383,  0.90830844,  0.96588737,  0.17373658,  0.87592824,
        0.75415641,  0.163486  ,  0.23784062,  0.85564381,  0.58743194])

In [72]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [73]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           1           0
1           0           0           0           0           1
2           0           0           0           0           1
3           1           0           0           0           0
4           0           0           0           0           1
5           0           0           0           1           0
6           1           0           0           0           0
7           0           1           0           0           0
8           0           0           0           0           1
9           0           0           1           0           0

## 7.3.9 String Manipulation

### 7.3.9-1. String Object Methods 

In [146]:
val = 'a, b, guido'

In [147]:
val.split(',') ## 쉼표(,)로 구분된 문자열은 분할된 문자열로 구분

['a', ' b', ' guido']

In [148]:
pieces = [x.strip() for x in val.split(',')] ##strip()을 이용해 공백 제거
pieces

['a', 'b', 'guido']

In [79]:
 'guido' in val 

True

In [80]:
 val.index(',') 

1

### *index()와 find()의 차이점
#### index()는 문자열이 없을 경우 ERROR발생
#### find()는 문자열이 없을 경우 '-1'

In [83]:
 val.count(',') ## count() : 문자열의 발생 횟수 반환

2

In [84]:
val.replace(',', '::') ## replace('a','b') : a를 b로 대체

'a::b::  guido'

[ 이외에 내장된 string method ]
- endswith, startswith : 접미사로 끝나는 경우 True반환(접미사로 시작)
- join : 문자열 삽입
- rfind : 하위 문자열이 마지막으로 발생한 첫번째 문자를 반환(찾을 수 없을 경우-1반환)
- lower, upper : 각각 소문자 or 대문자로 변환
- ljust, rjust : 문자열의 반대편에 공백을 붙여 반환

### 7.3.9-2 Regular expressions (정규 표현식)
#### 정규식은 복잡한 문자열을 처리할 때 사용하는 기법
#### 파이썬만의 고유 문법이 아니라 문자열을 처리하는 모든 곳에서 사용됨
#### regex : Regular expression  언어에 따라 형성된 문자열|

** re module 
    1. 문자열에 Regular expression을 적용하는 역할
    2. 기능은  pattern matching, substitution, splitting로 나뉜다

In [150]:
import re

In [89]:
text = "foo    bar\t baz  \tqux" ## \t : tab

In [90]:
#### split() : 지정 패턴이 발생할 때 나눔

In [91]:
regex = re.compile('\s+') ## \s+ : 1개 이상의 공백
regex.split(text)

['foo', 'bar', 'baz', 'qux']

#### findall() : 패턴과 일치하는 목록을 얻을 수 있음

In [178]:
text = "Rose rose@google.com Lisa lisa@gmail.com Jennie jennie@gmail.com Jisoo jisoo@yahoo.com"
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}' #[]안에서는 .의 효력을 잃는다.  {2,4} : 2~4개 사이
#http://gocoding.tistory.com/93 참고

regex = re.compile(pattern, flags=re.IGNORECASE) # ignorecase : 대소문자 무시
regex

re.compile(r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{3}', re.IGNORECASE|re.UNICODE)

In [179]:
regex.findall(text)

['rose@google.com', 'lisa@gmail.com', 'jennie@gmail.com', 'jisoo@yahoo.com']

#### search() : 문자열 전체를 검색하여 정규식과 매치되는지 조사

In [181]:
m = regex.search(text)
m #첫번째로 rose@google.com이 매치가 되었다.

<_sre.SRE_Match object; span=(5, 20), match='rose@google.com'>

In [185]:
text[m.start():m.end()]

'rose@google.com'

In [186]:
text[m.start():]

'rose@google.com Lisa lisa@gmail.com Jennie jennie@gmail.com Jisoo jisoo@yahoo.com'

In [99]:
#### match() : 문자열의 처음부터 정규식과 매치되는지 조사

In [100]:
n = regex.match(text)
print(n) ## match되지 않을 경우 None을 리턴
# text의 처음은 Rose이므로 pattern과 매치되지 않음

None


#### sub() : 정규식과 매치되는 부분을 다른 문자로 바꿈

In [102]:
k = regex.sub('REDACTED', text)
k

'Rose REDACTED Lisa REDACTED Jennie REDACTED Jisoo REDACTED '

####  사용자 이름, 도메인 이름 및 도메인 접미사로 분할시키기

In [187]:
# segment에 괄호를 쳐서 pattern 만들기 
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [188]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [189]:
regex.findall(text) 

[('rose', 'google', 'com'),
 ('lisa', 'gmail', 'com'),
 ('jennie', 'gmail', 'com'),
 ('jisoo', 'yahoo', 'com')]

In [190]:
a = regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text) 
print(a)

Rose Username: rose, Domain: google, Suffix: com Lisa Username: lisa, Domain: gmail, Suffix: com Jennie Username: jennie, Domain: gmail, Suffix: com Jisoo Username: jisoo, Domain: yahoo, Suffix: com


### 7.3.9-3. Vectorized string functions in pandas 

In [192]:
data = {'Rose':'rose@google.com','Lisa':'lisa@gmail.com','Jennie':'jennie@gmail.com','Jisoo':np.nan}

In [193]:
data = Series(data)
data

Jennie    jennie@gmail.com
Jisoo                  NaN
Lisa        lisa@gmail.com
Rose       rose@google.com
dtype: object

In [111]:
data.isnull() 

Jennie    False
Jisoo      True
Lisa      False
Rose      False
dtype: bool

In [112]:
#Series에서는 NA값을 건너뛰는 문자열 작업이 가능
data.str.contains('gmail')

Jennie     True
Jisoo       NaN
Lisa       True
Rose      False
dtype: object

In [194]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [200]:
data.str.findall(pattern, flags=re.IGNORECASE)

Jennie    [(jennie, gmail, com)]
Jisoo                        NaN
Lisa        [(lisa, gmail, com)]
Rose       [(rose, google, com)]
dtype: object

### 벡터화된 요소의 검색

In [115]:
matches = data.str.match(pattern, flags=re.IGNORECASE)
matches

Jennie    True
Jisoo      NaN
Lisa      True
Rose      True
dtype: object

In [116]:
matches.str.get(0)

Jennie   NaN
Jisoo    NaN
Lisa     NaN
Rose     NaN
dtype: float64

In [204]:
data.str[:5] # 5번째까지 문자 반환

Jennie    jenni
Jisoo       NaN
Lisa      lisa@
Rose      rose@
dtype: object

[ Vectorized string method ]
- cat : 구분 기호를 사용하여 문자열 요소 연결
- contains : pattern/regex 포함시 boolean array 반환
- count : 패턴 발생 수
- endswith, startswith : 접미사로 끝나는 경우 True반환(접미사로 시작)
- findall : 패턴과 일치 항목 반환
- get : 각 요소에 index처리
- join : 문자열 결합
- len : 길이 계산
- lower, upper : 대,소문자 변환
- match : 정규식과 일치하는 목록 반환
- pad : 문자열 양쪽에 공백 추가
- center : pad와 동일
- repeat : 중복 값
- replace : pattern/regex를 다른 값으로 대체
- slice : 문자열 절단
- split : 구분문자, 정규식 절단
- strip, rstrip, lstrip : 공백 제거